[package]
name = "you_cant_code_under_pressure_1"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

[[bin]]
name = "you_cant_code_under_pressure_1"
path = "main.rs"
